development:
  host: localhost
  database: macchiato_development

test:
  host: localhost
  database: macchiato_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>